### ISSUE TITLE
wintrt::initialize throws when already initialized

### ISSUE THREAD

**Issue by walbourn** [Microsoft/cppwinrt#53] opened 2016-12-14 20:38 UTC
In ``base.h``:

    inline void initialize(const initialize_type type = initialize_type::multi_threaded)
    {
        check_hresult(WINRT_RoInitialize(static_cast<uint32_t>(type)));
    }

You are allowed to call ``RoInitialize`` more than once but it returns ``S_FALSE`` if it's already initialized. The problem is that ``check_hresult`` only accepts ``S_OK`` and throws on ``S_FALSE``.

Either ``check_hresult`` should use ``FAILED(result)`` instead of ``result != S_OK`` or ``initialize`` should be implemented as follows to avoid using ``check_hresult``:

    inline void initialize(const initialize_type type = initialize_type::multi_threaded)
    {
        HRESULT result = WINRT_RoInitialize(static_cast<uint32_t>(type)));
        if (FAILED(result))
        {
            impl::throw_hresult(result);
        }
    }

**Comment by KevinWelton** [comment] 2016-12-14 22:02
This behavior is also discussed in [issue #8](https://github.com/Microsoft/cppwinrt/issues/8). The guidance is to only call winrt::initialize once, or to balance calls if necessary. We are avoiding injecting S_FALSE into cppwinrt in any way as the WinRT API surface is designed not to use it and it's avoidable in the initialize() scenario.

**Comment by walbourn** [comment] 2016-12-14 22:31
The problem is not merely balancing. The problem is that on some platforms you need to explicitly initialize Windows Runtime and on others you don't, so for portability you want to probably always call ``winrt::initialize``. With Windows Store/UWP, this fails as described because the runtime already initialized it.

I don't mind balancing the calls which makes sense. The problem is that if anything (CRT or otherwise) has already done the initialization, the current behavior results in an exception.

**Comment by KevinWelton** [comment] 2016-12-15 00:18
We need to look at the throwing behavior for another reason, the side-effect of which would solve your issue: we are treating RoInitialize as an error condition when it returns S_FALSE, whereas the documented behavior is that it should succeed _and_ be balanced by a corresponding call to RoUninitialize (winrt::uninitialized in our case) where it returns S_OK or S_FALSE.

Thanks for bringing this to our attention.

**Comment by tim-weis** [comment] 2016-12-15 20:21
@KevinWelton: I don't understand the rationale behind closing this issue (or [issue #8](https://github.com/Microsoft/cppwinrt/issues/8) for that matter). Neither one has been resolved in the published library, creating an unfortunate mismatch between code and documentation. Is there any chance of getting those back in sync in the future?

**Comment by kennykerr** [comment] 2016-12-15 22:45
The thing is that this is not a bug. The check_hresult function is used by the projection to handle WinRT errors and WinRT errors only account for the S_OK success code. You may use it yourself but its purpose is to deal with WinRT errors. If you need something else, feel free to write a helper function of your own. The same goes for winrt::initialize. It is a very low-level function used strategically to initialize the thread context in those corner cases where this is not done automatically on your behalf. If you need something more powerful or more general-purpose then feel free to write a tiny helper class that calls RoInitialize in its constructor and RoUninitialize in its destructor. This is not hard, but we’re not convinced that it is something that most developers need and that is why it is not included in the library.

**Comment by tim-weis** [comment] 2016-12-16 12:18
@kennykerr: I'd still argue, that this is a bug. As you explained in a [previous comment](https://github.com/Microsoft/cppwinrt/issues/8#issuecomment-254545051):
> RoInitialize [...] is not part of the WinRT API surface.

`check_hresult`, on the other hand, is implemented in a way that allows it to be used on the WinRT API surface only. In short, `initialize` mixes different interface contracts in its implementation.

Even if you disagree with the assessment, that this were a defect, it's still an issue that users of the library need to be aware of. Providing documentation reflecting the current implementation is one way to achieve that. And that's why I was surprised to see this issue closed, while the published library code still implements this behavior.

I'm not requesting to have the implementation changed. I'm only asking for documentation that matches the implementation, to help us developers use this library reliably.

**Comment by kennykerr** [comment] 2016-12-16 16:02
Sorry for the confusion. We maintain both a private and public repo. We hope to move entirely to the public repo in the future, which will make all this a lot less confusing. I can confirm that we will update winrt::initialize to report errors and non-errors consistently with the underlying RoInitialize call. I’ll leave this issue open until that change has made its way to the public repo. Thanks for the feedback!

**Comment by Zingam** [comment] 2016-12-23 17:00
I read in a document that to achieve the behavior:
```
[Platform::MTAThread]
int main(Platform::Array<Platform::String^>^)
```
We need to call `winrt::initialize()`. But calling it in  a UWP app causes a crash. So what is the default behavior? Is it documented somewhere?

**Comment by kennykerr** [comment] 2016-12-23 17:35
Both the non-standard C++/CX MTAThread attribute and the winrt::initialize function cause the RoInitialize function to be called to initialize the thread context. The Visual C++ CRT calls RoInitialize before execution arrives at WinMain for UWP store apps, but not for desktop/console apps. That's why it fails: it's already been initialized.

**Comment by kennykerr** [comment] 2017-03-03 16:17
The init_apartment function (formerly called initialize) will no longer throw if it is called repeatedly (redundantly) on the same thread. The check_hresult function has been improved with support for other success codes, as an opt-in feature.

**Closed by kennykerr** 2017-03-03 16:17 UTC
Labels: addressing
