### ISSUE TITLE
single_threaded_vector().GetView() causes crash when used with .NET Native.

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/cppwinrt#736] opened 2020-08-27 18:57 UTC
When passing the `IVectorView<T>` to C# code, a crash happens in NET Native when trying to enumerate the collection.

The reason is that the `GetView()` method returns the same object back, just with a different interface. This means that the view's `GetRuntimeClassName` reports that it is an `IVector<T>` instead of `IVectorView<T>`, which messes up COM interop with .NET Native.

**Comment by kennykerr** [comment] 2020-08-30 15:39
I've been meaning to add simple `vector_view` and `map_view` functions that don't implement the mutable interfaces at all and can rely on much simpler internal locking for all scenarios. Such dedicated view implementations would solve this problem and more.

**Comment by benstevens48** [comment] 2020-09-15 21:05
Are you able to elaborate on exactly when this bug occurs? I noticed the title of the issue and realized it would be very bad for my project if this were indeed the case, but I can't reproduce the bug.

**Comment by kennykerr** [comment] 2020-09-16 15:59
I haven't seen the repro, and for the most part C++/WinRT collections work just fine with C# consumers. I don't actually consider this a C++/WinRT bug. Relying on what `GetRuntimeClassName` returns for non-classes is rather dubious to begin with. The fact that some language projection relies on this rather than `QueryInterface` is the real bug. Anyway, this is mostly about hardening C++/WinRT to improve compat.

**Comment by benstevens48** [comment] 2020-09-21 12:07
Having said that I couldn't reproduce the issue, I've now hit the crash in my app. I'll give the repro (which is bizarre) below, but first I have a few comments on the suggested workaround in #743. 

I don't understand the discussion about threading. Surely since everything is read-only, no locking/synchronization is needed. It's true that the iterator position changes, but surely a new iterator object is returned whenever the caller starts an iteration over the list, so I don't see why this requires locking (unless you expect the caller to share the iterator with another thread and use it simultaneously, but that would be quite weird). Therefore the workaround that I've come up with (I needed an immediate fix for my app), based on @jlaanstra's very helpful code in #743 and also the [docs](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/collections#base-classes-for-collections) is the following (`CreateCustomVectorView`).

```C++
    namespace WinrtHelpersImpl {
        namespace wfc = Windows::Foundation::Collections;

        template <typename T, typename Container>
        struct CustomVectorViewImpl : implements<CustomVectorViewImpl<T, Container>, wfc::IVectorView<T>, wfc::IIterable<T>>, vector_view_base<CustomVectorViewImpl<T, Container>, T>
        {
            static_assert(std::is_same_v<Container, std::remove_reference_t<Container>>, "Must be constructed with rvalue.");

            explicit CustomVectorViewImpl(Container&& values) : m_values(std::forward<Container>(values)) {}

            auto& get_container() const noexcept {
                return m_values;
            }

        private:
            Container const m_values;
        };
    }

    template <typename T, typename Allocator = std::allocator<T>>
    Windows::Foundation::Collections::IVectorView<T> CreateCustomVectorView(std::vector<T, Allocator>&& values = {}) {
        return make<WinrtHelpersImpl::CustomVectorViewImpl<T, std::vector<T, Allocator>>>(std::move(values));
    }
```

(I would really appreciate if you could point out anything wrong with that). I can confirm that using `CreateCustomVectorView` on a std::vector instead of calling GetView() on an IVector created using single_threaded_vector fixes the crash, and also get_class_name returns the 'correct' value of `Windows.Foundation.Collections.IVectorView<T>`.

In my opinion the crash is quite a serious one and should be fixed properly (and ideally asap) by modifying GetView so it works, as well as offering the vector_view function to easily create a read-only IVectorView. It ought to be quite easy to fix GetView by returning a simple wrapper around the IVector that implements the IVectorView and IIterable interface methods by proxy. I understand that this is not really a C++/WinRT bug, but rather a flaw in .Net Native. However, standing outside Microsoft, this is sort of an implementation detail, and I can't see this being fixed in .Net Native any time soon, whereas C++/WinRT has the chance to fix it quite quickly (which is one of the strengths of C++/WinRT), so hopefully that can happen.

### The repro
Here is a rough outline of the C++/WinRT component class called `Class` (this method has an obvious MIDL defintiion).
```C++
Windows::Foundation::Collections::IVectorView<Windows::Foundation::Numerics::float2> Class::GetVectorView() {
	std::vector<Windows::Foundation::Numerics::float2> vec{ Windows::Foundation::Numerics::float2{1.0f, 2.0f}, Windows::Foundation::Numerics::float2{3.0f, 4.0f} };
	return winrt::single_threaded_vector(std::move(vec)).GetView();
}
```
Now here is a C# method which crashes when compiled with .Net Native.
```C#
        private async void TestVectorView() {
            var cls = new Class();
            var view = cls.GetVectorView().ToList();
            t1.Text += "Got view";
            await Task.Delay(5000);
            var str = JsonConvert.SerializeObject(view);
            t1.Text += str;
        }
```
Note t1 is a text box. I added the delay to prove that the crash happens on the line `cls.GetVectorView().ToList()`.
There is no crash in the following circumstances: remove the `ToList()` or remove the `JsonConvert.SerializeObject(view)` (this is a Newtonsoft.Json method - it's clearly not the cause of the problem because the crash happens on the ToList line, but it was the first thing I tried to add that could make the crash occur). Even more bizarrely, adding additional methods to Class.idl before GetVectorView() may prevent the crash - I added one which returned an IVector to investigate the behavior and then the crash with GetVectorView no longer happened!

On a final note, without the `ToList`, JsonConvert.SerializeObject will serialize the view to `{}` instead of an array of vectors. I don't know if this is a Newtonsoft.Json issue, an issue that can't be resolved, or an issue that could be fixed in C++/WinRT by implementing an additional interface on the underlying object behind IVector/IVectorView or something like that.

**Comment by DefaultRyan** [comment] 2020-09-22 17:41
Thanks for all the details! I'll start looking into this.

**Comment by kennykerr** [comment] 2020-12-17 03:07
https://github.com/microsoft/cppwinrt/pull/822#issuecomment-747152383: That makes me think that perhaps a better solution is for GRCN to return a per-interface value instead of a per-instance value. Then it would always match the vtable. Obviously for the default interface of a class it would still have to return the class name. And the collection implementations wouldn't have to change at all.

**Comment by benstevens48** [comment] 2020-12-17 10:32
@kennykerr - Are you talking about changing the behavior for all interfaces or just the IVectorView one? If you mean all interfaces, I'm not sure if this is a good idea because the docs state that `The GetRuntimeClassName method provides the most specific type information that the server object guarantees that it implements` and it's possible this is relied upon somewhere. Although if the .Net Native people and anyone else who uses GetRuntimeClassName are sure this is OK then I guess you could change the behavior.

Alternatively, perhaps you could arrange it so that the default behavior is the same as it is currently, with the ability to override for a specific interface, then just override it for IVectorView (and other I...View interfaces). I don't know how easy this would be though. In fact if you could override it for a specific implementation only such as the vector_view_base implementation using an extension point or something then that would be ideal.

**Comment by kennykerr** [comment] 2020-12-17 15:33
C++/WinRT has always done its best to ensure accurate type information reporting, but only for classes. This would simply ensure the reported type information is accurate for interfaces as well. This is not optional or something implementations should override as COM relies on it for marshaling, and evidently .NET relies on it as well. This change would merely ensure that GRCN always returns the most specific runtime name of the type that a particular `IInspectable` interface pointer actually implements.

**Comment by kennykerr** [comment] 2020-12-17 16:27
I just checked and ironically, C++/CX implements GRCN the same way C++/WinRT does. It would cause the same crash in .NET.

**Comment by benstevens48** [comment] 2020-12-17 16:29
What I was saying is that the docs currently suggest that the value is per-instance (they use the language "object" but I assume that means the same thing). So previously if you for some reason cast a class instance to an interface then call GetRuntimeClassName, you would get the same value as calling GetRuntimeClassName on the class. Also, if two projected IInspectables compare equal then they will return the same GetRuntimeClassName. Maybe I've misunderstood, but it seems that you are proposing to change that behavior, which seems like it has the potential to break things.

**Comment by kennykerr** [comment] 2020-12-17 16:40
Obviously such a change would only be made if it broke less things. 😉

**Comment by benstevens48** [comment] 2020-12-17 17:18
Fair enough, it just seems quite scary to me to make a change to the behavior of one of the methods on the base interface for all of WinRT! But for those with knowledge of how GetRuntimeClassName is actually used, perhaps it's less scary...

My suggestion was a bit of a hack to limit the change to just the case where it's needed (which isn't really ideal but was slightly less scary from my point of view).

**Comment by jlaanstra** [comment] 2020-12-17 19:03
> I just checked and ironically, C++/CX implements GRCN the same way C++/WinRT does. It would cause the same crash in .NET.

Currently CX does not cause this crash. Is that simply because CX does return a new object for GetView()?

**Comment by kennykerr** [comment] 2020-12-17 19:08
CX itself will cause the crash. The stock CX implementation of `IVector` (inside `collections.h`) returns `IObservableVector`'s name from GRCN because that happens to be the first interface listed under the CX implementation. And since that interface has no useful members (in most cases), .NET is forced to query for something else and thus avoids the crash. Had the CX stock implementation happened to list `IVector` first it would also crash.

**Comment by jlaanstra** [comment] 2020-12-17 19:19
> CX itself will cause the crash. The stock CX implementation of `IVector` (inside `collections.h`) returns `IObservableVector`'s name from GRCN because that happens to be the first interface listed under the CX implementation. And since that interface has no useful members (in most cases), .NET is forced to query for something else and thus avoids the crash. Had the CX stock implementation happened to list `IVector` first it would also crash.

Interesting. However the VectorView implementation returned by GetView() in CX seems to only have IVectorView listed and so would be correct right? Based on https://github.com/microsoft/cppwinrt/issues/736#issuecomment-747174668 are you still planning a change here?

**Comment by kennykerr** [comment] 2020-12-17 19:28
Yes, it's `GetView` implementation happens to create a new object and lists `IVectorView` first so that's why it works in that case. In hindsight that would have been better and given a new collection implementation I'm sure I'd do that. 

> are you still planning a change here?

Not at this time. I'm not really sure there's an obvious solution that will satisfy everyone.

**Closed** 2020-12-17 19:37 UTC
Labels: enhancement
