### ISSUE TITLE
MDM2009 duplicate type error when using a grandchild reference

### ISSUE THREAD

**Issue by RealTommyKlein** [microsoft/cppwinrt#452] opened 2019-12-13 02:54 UTC
Scenario: creating a CppWinRT app "App" with two WinRT components "B" and "C" with the following dependencies/references:

- App references B and C
- B references C

B will copy C.winmd to its output directory since it's a dependency.  App will pass B and C's output directories as metadata directories to mdmerge since they are dependencies.  However, because C.winmd is present in both B and C's output directories, App's mdmerge will fail because it detects duplicate types in the two C.winmds it evaluates.

**Comment by mediabuff** [comment] 2019-12-18 10:03
Any fix in sight ? A show stopper for real world cppwinrt apps. This important issue was raised 6 months back (#318, #454), . MS folks closed it without any reason. Is MS (all related teams in MS) serious about supporting c++ and xaml ?

**Comment by kennykerr** [comment] 2019-12-18 18:17
The msbuild support is a volunteer effort at this stage. @jlaanstra is doing most of that volunteering and hopefully he can get to this one at some point. As a workaround, you can always call midlrt, mdmerge, and cppwinrt from pre and post build steps. That's what I typically do and it works reliably. It's harder to set up, but more complex C++/WinRT projects tend to do just that. You can also restructure your project to avoid the dependency graph issues above. As for C++ and Xaml, I don't think that's going to be practical until C++ supports reflection and can produce the metadata that the Xaml toolchain requires. Again, it can be done manually but it is hard. The Xaml framework itself is built that way. https://github.com/Microsoft/microsoft-ui-xaml

**Comment by mediabuff** [comment] 2019-12-18 18:36
Kenny, thanks for your response. I am not convinced by your arguments. One app referencing a DLL and that in turn referencing another DLL ? Complicated ? We have total broken tool chain even for the simplest of the use cases. MS teams don't seem to get their collective act together. This doesn't require 'reflection' etc. I don't think any body in MS is seriously using cppwinrt with the delivered and publicly available toolset. This is in sane - after how many years of winrt/UWP/Xaml - we can't seem to develop simple apps in c++.

>> can also restructure your project to avoid the dependency graph
I am not sure the issue is being genuinely understood.  Your suggestion is not possible. This is the same guidance I got one year back. One app and one control library reference standard Win2D package ? how will you break transitiveness ?

**Comment by kennykerr** [comment] 2019-12-18 18:49
You're preaching to the choir. I realize the we have problems ([darkness](https://kennykerr.ca/2015/05/26/a-second-dark-age-for-c/), [xaml](https://kennykerr.ca/2019/01/25/the-state-of-cpp-on-windows/)) and I continue to champion those within Microsoft, but there's only so much I can do. 

> I don't think any body in MS is seriously using cppwinrt the inbox/publicly available toolset.

That's not entirely true. There are a few heavily used MS apps that use both C++/WinRT and its build support. There are also many many top apps for Windows that use C++/WinRT (with or without build support) including many Windows and Office apps, Adobe products, Spotify, and much more. 

So yes, Visual Studio integration continues to be a sore point and developing "simple" apps with C++ may not be that practical but investing in large scale development with C++/WinRT has certainly been very successful for many professional developers.

**Comment by mediabuff** [comment] 2019-12-18 19:14
Others may using this for non-Xaml work effectively or simpler single DLL situations like Microsoft.UI.Xaml. . For Xaml apps, we a long way to go. This particular issue is not build tool issue. I have tried various complicated Msbuild scriptis to intercept midlrt - but was fighting against a conceptual problem in mdmerge. There is a fundamental arch issue with midlrt/mdmerge. Can only be fixed by fixing midlrt/mdmerge. Would be glad to help - but these tools are not open source.

**Comment by kennykerr** [comment] 2019-12-18 19:20
Yes, midlrt and mdmerge have many problems. I'm working very hard to make those tools unnecessary in the future, but that's [another story](https://kennykerr.ca/2019/11/05/rust/). 😉

**Comment by jlaanstra** [comment] 2019-12-19 03:42
This is something that needs to be addressed in mdmerge.exe which ships as part of the Windows SDK. As a workaround you can use:

```
<ItemDefinitionGroup>
    <Reference>
        <Private Condition="'$(ConfigurationType)' != 'Application'">false</Private>
    </Reference>
</ItemDefinitionGroup>
```

**Comment by mediabuff** [comment] 2019-12-20 00:46
Thanks for a potential approach. I assume this goes in project B's project reference to C ? Let me try this. The challenge is Win2D is referenced by a nuget install via Win2D.uwp.targets. So there is no direct reference in project B.

**Comment by jlaanstra** [comment] 2019-12-25 14:07
@mediabuff the above simply changes the default for all items in the Reference itemgroup, so as long as Win2D doesn't explicity set it to true (which it shouldn't), this should work correctly.

**Comment by mediabuff** [comment] 2020-01-15 18:04
hi all,
Doesn't help, as this is already the case. The hurting winmd/dll is Win2D, whose targets already have the private property.

Easily reproducible. Create a UWP blank app, a UWP control dll and have both of them reference Win2D. All Microsoft software out of the box.

Package: https://www.nuget.org/packages/Win2D.uwp/1.24.0
Target:    packages\Win2D.uwp.1.24.0\build\native\Win2D.uwp.targets

`<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <win2d-Platform Condition="'$(Platform)' == 'Win32'">x86</win2d-Platform>
    <win2d-Platform Condition="'$(Platform)' != 'Win32'">$(Platform)</win2d-Platform>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="$(MSBuildThisFileDirectory)..\..\lib\uap10.0\Microsoft.Graphics.Canvas.winmd">
      <Implementation>Microsoft.Graphics.Canvas.dll</Implementation>
	  <Private Condition="'$(ConfigurationType)' != 'Application'">true</Private>
    </Reference>
    <ReferenceCopyLocalPaths Include="$(MSBuildThisFileDirectory)..\..\runtimes\win10-$(win2d-Platform)\native\Microsoft.Graphics.Canvas.dll" />
  </ItemGroup>

  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory)..\..\Include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>

  <Import Project="$(MSBuildThisFileDirectory)..\Win2D.common.targets" />

</Project>
`

**Comment by mediabuff** [comment] 2020-01-15 21:41
This can be easily resolved if MDMERGE to provide an option to merge only 'given files' and not all file in a directory;.

**Comment by danzil** [comment] 2020-01-17 20:59
I agree with @mediabuff where they say this is a core scenario that should be working. This is currently blocking a portion of the UWP and WinUI Xaml Compiler regression tests. Those tests used to work just fine until 19H1, then we started encountering a series of regressions from the MIDL compiler that we never really recovered from. We appreciate all the voluntary work that Johan is pouring into this, no question about that, but really, the team behind MIDL and cppwinrt should jump in and help as soon as possible because this is a regression and a core scenario that hurts the developers adopting the technology. It's important enough to reevaluate that P2 priority this is currently sitting on.

**Comment by kennykerr** [comment] 2020-01-17 21:02
Thanks all. I've assigned the issue to @BenJKuhn who has to make the call whether to invest in midl/mdmerge to get this fixed.

**Comment by mediabuff** [comment] 2020-01-23 03:59
If MS doesn't have the resources, please open source it. This should be easy enough to fix.

**Comment by kennykerr** [comment] 2020-01-28 16:00
I'd love to, but open sourcing is a much bigger task sadly. These tools are just very deeply buried in the OS repo. Hopefully one day, but in the meantime @jlaanstra is working on a fix to mdmerge.

**Comment by kennykerr** [comment] 2020-02-03 20:17
Closing this issue as it is outside the scope of the C++/WinRT project and the fix Johan has been working on is not part of C++/WinRT.

**Closed by kennykerr** 2020-02-03 20:17 UTC
Labels: bug

**Comment by mediabuff** [comment] 2020-02-04 13:16
>>fix Johan has been working on is not part of C++/WinRT.
Where is this being tracked ? Hope MS doesn't drop this once again.

**Comment by shelllet** [comment] 2021-02-19 02:10
how to resolve by manual?
