### ISSUE TITLE
Unable to add C++/WinRT Runtime Component to UWP C# Application

### ISSUE THREAD

**Issue by Code-ScottLe** [microsoft/cppwinrt#425] opened 2019-11-15 19:50 UTC
Just want to make sure that I'm not doing something wrong here. I have created a Runtime Component project , implemented a bare minimum of a single Runtime class (following the example here: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-events), but i could not reference this project from a C# UWP Application within the same solution. Trying to add a reference to the project would just end up with the message of `The method or opration is not implemented` . Is this a known issue with Visual Studio or C++/WinRT? Project referencing from a C++/WinRT Blank application doesn't have this issue.

Directly referencing the winmd files under Debug\Merged\ will just result in a runtime exception of something not activated class. 

Also, if i tried to manually reference the project by editing the csproj file manually, I have 2 cases happening. One project works just fine and the other one is complaining about not having the DLL of the Runtime Time component under its `Debug` folder. 

I can try to upload both projects here (the one that kinda-works and the one that doesn't) later but if anybody have any pointers, that would be great.

**Comment by kennykerr** [comment] 2019-11-18 17:07
> The method or operation is not implemented

Did you provide an implementation? The default for a component project is to generate stubs that throw an exception.

**Comment by Code-ScottLe** [comment] 2019-11-18 17:51
[TestWinRT.zip](https://github.com/microsoft/cppwinrt/files/3859897/TestWinRT.zip)

Here is the example. The Runtime Component project is the BankAccountWRC. It can be added to the BlankApp1 (a C++/WinRT UWP app), but when trying to add to App1 (C# UWP) VS won't allow to do such things.

However, if you modify the csproj of App1 to have a project reference manually, you can get it to build. However, this is not guaranteed as i was not able to get it to build on others projects that might complain about missing DLLs. 

This works:
![image](https://user-images.githubusercontent.com/10987612/69076275-faeaab00-09e7-11ea-81e9-f5a60a05bdcb.png)

This does not:
![image](https://user-images.githubusercontent.com/10987612/69076779-0be7ec00-09e9-11ea-91db-94416aadaff9.png)

**Comment by Code-ScottLe** [comment] 2019-11-18 20:40
Is there an example somewhere that have the C# UWP and C++/WinRT Runtime component working together? I couldn't find any example to follow on rather than the MS Docs link above on how to implement a Runtime Component.

**Comment by kennykerr** [comment] 2019-11-19 17:24
Cross language support in Visual Studio is not very robust. I believe you can get it to work if you reference the winmd directly and then also make sure that the necessary build artifacts (including .winmd files and .dll files) are copied to a shared build directory so that the loader can find them all. This is admittedly non-trivial, but not something I really have any say over. My suggestion is to bring up the issue here:

https://developercommunity.visualstudio.com/spaces/62/index.html

The benefit of doing so is that it will immediately create an issue (a bug report) with the Visual Studio team. If you then link back to the issue here, we can bump the issue internally to make sure it gets attention.

**Comment by Code-ScottLe** [comment] 2019-11-19 20:24
@kennykerr Just want to be sure, the only winmd file that i need to manually reference is in the {project_root}/Debug/Merged folder? I don't think i see any other dlls. And when i try to manually reference the winmd files, this happens:

![image](https://user-images.githubusercontent.com/10987612/69183195-65bee380-0ac7-11ea-8651-8e52d324b3f4.png)

**Comment by kennykerr** [comment] 2019-11-19 20:30
Yes, that looks right. Also, "Class not registered" typically means the loader doesn't know how to find the type. This is distinct from whether or not you have the dll/winmd present. Typically that is done via a manifest of some kind.

**Comment by Code-ScottLe** [comment] 2019-11-19 20:35
Then how would a normal user would reference a runtime class from a C# UWP app then? All i did was to add a reference to the winmd file that was built from the C++/WinRT project. I don't think i have ever have to touch a manifest file to get a class loaded in.

**Comment by kennykerr** [comment] 2019-11-19 20:47
Are you referring to this problem when adding a project reference? I just tried this now and this is what I get when trying to add a project reference from a C# UWP app to a C++/WinRT component project. @jlaanstra this was working before. Any ideas?

![image](https://user-images.githubusercontent.com/9845234/69184850-82a8e600-0aca-11ea-8918-5bbb3b87f4ae.png)

**Comment by Code-ScottLe** [comment] 2019-11-19 20:50
Yes, so there are total of 2 problems here:
1. The screenshot above. Unable to add the C++/WinRT Project reference to a C# UWP app with VS.

2. Adding the Winmd file to the C# UWP app will result in runtime exception of TypeLoadException.

**Comment by kennykerr** [comment] 2019-11-19 21:05
Assigning to @Scottj1s - thanks for reporting this issue.

**Comment by Scottj1s** [comment] 2019-11-25 15:42
@Code-ScottLe - note that this scenario requires reg-free winrt activation from the C# app.  I don't see that in you package.appmanifest.  For details, see:
https://github.com/microsoft/xlang/wiki/Referencing-a-Windows-Runtime-component-from-a-Desktop-app

**Comment by Scottj1s** [comment] 2019-11-25 18:03
@jlaanstra, with further investigation, this looks like a regression from [this commit](https://github.com/microsoft/cppwinrt/commit/db382832f52e5fdb25d990586762c2fec82cce1b#diff-82b5687ed66e731f5e32dad6c7c5360d).  Flipping the GenerateWindowsMetadata project property to false has the unintended consequence of preventing direct project references from a C# app to a native RC dll.  The project/manifest edits mentioned above should only be necessary when the app is not UWP.

**Comment by Scottj1s** [comment] 2019-11-25 18:06
@Code-ScottLe - a better workaround, based on the identified regression, is simply to add <GenerateWindowsMetadata>true</> to your project.

**Comment by Code-ScottLe** [comment] 2019-11-26 08:42
@Scottj1s 
> a better workaround, based on the identified regression, is simply to add <GenerateWindowsMetadata>true</> to your project.

Where should i add this? Inside the vcxproj? I just tried but it still doesn't work. Will be trying the other method shortly.

![image](https://user-images.githubusercontent.com/10987612/69612989-a0ec7580-0fe5-11ea-8f9f-7e4f765440aa.png)

**Comment by Code-ScottLe** [comment] 2019-11-26 21:12
I can confirm that following the second steps of manually adding the bits to the csproj "works". However, i don't think if that is something that everybody would want to do however.

**Closed** 2019-11-27 19:23 UTC
Labels: bug

**Comment by yves-dolce** [comment] 2020-03-11 01:05
This scenario should definitively be formally documented somewhere. Thanks to the information I found here, I was able to make the scenario work but I believe this is going to become a too common for a developer to be lucky enough and find this page.
Additionally, it seems that several things can influence the proper reference to the .winmd and .dll file from the C# projects.
Or is it well documented and I have not found it? ;-)

**Comment by BinaryNate** [comment] 2020-09-02 23:20
+1 for formally documenting the need for `<ActivatableClass/>`. I am a library author and my use case is that I needed to replace a small C#-based runtime component with an equivalent C++ based runtime component in order to prevent my clients from having to include the CLR or compile with .NET Native (for context, the library is for UWP apps produced with Unity's IL2CPP scripting backend). With the the C#-based runtime component, all that was needed in client applications was to add a reference to the winmd file. However, it took me a day of research and trial and error to figure out that in order for a client app to use my new C++ based runtime component, a reference must be added to the DLL (in addition to the winmd file) and an `<ActivatableClass/>` section must be added to the app manifest. Documenting these requirements in the [Creating a Windows Runtime Component article](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/create-a-windows-runtime-component-in-cppwinrt) could help prevent others from having a similarly difficult time.

- 
-

**Comment by tero-paananen** [comment] 2020-09-03 12:34
I did not managed to build WinRT C++ runtime component into C# app with latest VS. Example project where that works could be needed?

**Comment by HppZ** [comment] 2021-08-03 10:50
same issue for me.
