### ISSUE TITLE
Win32 Desktop app and UWP app

### ISSUE THREAD

**Issue by anhoavu** [Microsoft/cppwinrt#229] opened 2017-08-21 19:15 UTC
Is it possible to make use of UWP's UI elements in a traditional UWP desktop app with C++/WinRT?

**Comment by kennykerr** [comment] 2017-08-24 15:27
While the Windows Runtime provides many APIs that may be used from desktop apps, the Windows.UI APIs currently require an app container. This may change in the future. Many of us certainly hope it does. 😄

**Comment by raffaeler** [comment] 2017-08-24 15:41
This would be a hugely welcome change!
There are several problems with  UWP right now:
- the inability to run admin code without using Centennial
- the immaturity of the app lifecyle, probably due to problems with Explorer.exe (I often face to Microsoft UWP apps that doesn't close with "x" and I have to kill 'em).
- not having an unified XAML infrastructure with WPF (which is the 'reference implementation' as it implements more features even if has several weaknesses).
- the over-over-over-complicated deployment system is a huge blocker for companies

my 2 cents

**Comment by therealkenc** [comment] 2017-08-24 22:38
I am presently tinkering with a project related to this. There is a bunch of good information over at the the Desktop Bridge [launch point](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root) on Dev Center. In particular there is new stuff in the Fall Creators Update, available in the [16267 pre-release](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK) of the SDK which allows "full trust" marshalling of WRT objects between desktop apps and the app container. There is a good blog post [here](https://blogs.windows.com/buildingapps/2017/07/06/calling-winrt-components-win32-process-via-desktop-bridge/#GOdiPReWvveycZaB.97). Something along the lines of the [WinFormsWinRTComponent](https://github.com/Microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples/WinFormsWinRTComponent) Calculator would make a _really helpful_ cppwinrt sample once the compiler is released. For me anyway.

Kenny - if MSFT is even _considering_ allowing Windows.UI.Xaml APIs outside the app container that would be freaking awesome. To the extent you have any kind of pull around the office please do what you can to advocate for this (without getting fired). I do "get" sandboxed environments. I really do. Been involved with large Java projects since the 1990s. But the present situation just means developers are going to keep using WPF and Forms. Call them "enterprise" or "legacy" scenarios if it makes people feel better (they aren't of course). But whatever it takes.

**Comment by raffaeler** [comment] 2017-08-25 06:41
@therealkenc Unfortunately the marshalling is not enough. I have customers in the healthcare environment with very high refresh rate videos needing to access memory shared from a driver. Doing the math, there is no other way to do that. The UWP presentation layer works over three rendering threads and share DX surfaces while WPF is out of business but it is the only way to gain admin pivileges. End of the game.

I have other cases where the marshaling could work in theory but is an overkill compared to the way a typical desktop app works.
I understand and share the need of a sandbox for most of the apps, security is super-important. But it is not all black or white, there are many cases where you need to have full privileges.

**Comment by kennykerr** [comment] 2017-08-25 15:46
I asked the UI teams and it turns out that this has been the top ask on User Voice for some time.  

https://aka.ms/windowsui/inwin32

Please elaborate on your scenario needs on User Voice. This helps us prioritize the things that matter in real cases over the hypothetical ones. We're listening. 😉

**Comment by DBJDBJ** [comment] 2017-08-28 07:20
@kennykerr  Thanks 
@raffaeler If I may? Basically I "was there" way back in 2000. Funny thing is solutions (for real time video) have not changed since then. I have delivered COM/ActiveX based on quartz.dll ... which was used from IExplorer (was it 4?!). We could have 12 realtime simultaneous videos inside the same html page. 17 years ago. The point is: we are  back to that time. UWP .NET XAML WPF do not deliver for realy demanding UI requirements. DX? Perhaps, but I do find it very rewarding to go "arround" DX. API is over engineered.

**Comment by raffaeler** [comment] 2017-08-28 07:33
@DBJDBJ agree.
DX works pretty well in UWP but the data rate transfer from the source (healthcare machine) is too demanding for any other system different from memory share. It is not a classic highres video.
There are many other cases where companies, which have a different target from an end-user app, need admin privileges and solutions requiring a broker are an overkill for the amount of work needed to transfer and the resources involved.
For example if  you have a broker running as admin on localhost, it must be protected from being accessed from other parties out of the app. It is definitely possible but you should use a certificate and there is no built-in support to do it. At that point, it is far better to stay on a desktop app that offers more XAML features, can be run as admin and you don't have to bother on the activation and deployment issues of UWP apps that frankly, after 3 OS versions, are still bad implemented.

**Comment by walbourn** [comment] 2017-08-28 09:40
From a security perspective, having the ability to run 'as admin' for UWP is overkill and undesirable in a modern appmodel. What specific aspects of the huge list of privileges that go with admin do you actually need?

**Comment by raffaeler** [comment] 2017-08-28 09:43
@walbourn it is certainly not something that you need for most of the apps! And I totally share the need of sandboxing the code.
Said that, there are scenarios where you need to access features of the OS that are available only as admin.
In certain cases it may be simple to use a broker (either the ones provided from WinRT or your own).
In other cases the brokers cannot be used because they kill performance such as the case I explained above (shared memory with drivers).
It's not all black or white ...

**Comment by Scottj1s** [comment] 2017-08-28 13:22
@raffaeler, your point is well taken.  I'd be careful to distinguish an individual API from the API technology.  WinRT does permit many APIs to run outside of the appcontainer sandbox restriction (these are marked with the [DualApiPartition](https://docs.microsoft.com/en-us/uwp/api/Windows.Foundation.Metadata.DualApiPartitionAttribute)).  Some of these APIs may be appropriate to run in as admin in a desktop context, but those would by definition exclude app execution.

**Comment by raffaeler** [comment] 2017-08-28 13:40
@Scottj1s The distinction is perfectly clear but there are few things to take into account:
1. Currently WPF has poor rendering performance in comparison to UWP that is also able to share DX surfaces. This prevents doing the admin stuff in WPF because the UI model in UWP is only available inside the appcontainer. But the appcontainer cannot run as admin ...

2. With Centennial you basically allow a mix but this "exception" is only valid for app written with normal desktop APIs which is not interesting for me.
I wish to have the "full control" as Centennial processes have, but using the full-fledged UWP APIs, not just those marked as dual partition.

IMO these are the reason why many companies did not embrace UWP or Centennial. If you have to spend money for a new app release, you want to invest in new technologies, not just putting a wrapper around the old code. That is not an investment, is just wasting time (let me repeat, IMO).
Thanks

**Comment by walbourn** [comment] 2017-08-28 14:18
With respect to the PC, UWP and Win32 desktop apps are complementary. IF you need admin rights, then Win32 desktop already solves this scenario. It seems like the basic ask here is really "update WPF for modern DirectX features for better performance" since it seems like very little of your scenario is actually intended to be addressed by UWP apps.

While there are certainly platform specific scenarios, most of the design decisions around UWP make a lot more sense if you think across PC, Xbox, mobile, and IoT as a class of devices using the same appmodel. "Running as an admin" simply doesn't make sense on most of these devices, and as I stated at the outset is not particularly desirable behavior even on PC.

**Comment by raffaeler** [comment] 2017-08-28 14:36
@walbourn The "WPF airspace problem" has been solved a long time ago in a service pack and for some reason removed in the next release. There is no cooperation between DX and WPF anymore, at least not without hacks. It is probably a dead-end that will nevermore be resolved IMO.

I totally subscribe the strategy to add "capabilities" for apps targeting the end user on the store.
But this strategy is not suitable for company internal apps or tools that need to interact heavily with the OS:  starting/stopping services, accessing WMI, accessing Hyper-V, running configuration scripts, etc.
Yes, you may add even more capabilities, but working with a broker in the middle is definitely not the same thing.

I also totally subscribe that in most of the cases there is no need to run an app as admin, but I don't get why you don't give this chance as it was a special "capability" (preventing to publish on the public store) so that companies can leverage the same technology everywhere instead of jumping from WPF to UWP and vice versa with a lot of trouble in sharing incompatible code.

Also, if your answer is to "go back" to desktop apps, why are you pushing on Centennial? What is the need to migrate to UWP for enterprise-wide apps (where there is no public store involved)?

**Comment by walbourn** [comment] 2017-08-28 15:02
I'm not familiar enough with your scenario to make any real judgment here, I'm just stating that "UWP" and "Run as admin" are likely in irreconcilable conflict.

Centennial is about leveraging AppX deployment, packaging, and update for Win32 desktop apps and using the AppContainer 'sandbox' (although that's not really an ideal description of the ACL boundaries). They aren't truly "UWPs" in any real sense.

Anyhow, there are better venues for user voice requests so I was mostly just trying to provide some additional perspective to the discussion thread. In any case, there's no much actionable here for the C++/WinRT team proper.

**Comment by anhoavu** [comment] 2017-08-28 19:57
@kennykerr Thanks for your response. I have an existing UWP app but some features require system access so I want to make a Win32 version for customer who wants those features and keep providing the UWP version for those who don't. Thus, I hope to use a single code-base in C++ that can be configured to build those 2 versions.

**Comment by therealkenc** [comment] 2017-08-29 06:51
>  In any case, there's no much actionable here for the C++/WinRT team proper.

@walbourn - I hope you can be convinced to change your worldview on that, even a little. We got lost in "administrative privileges" here a bit. The problem is missing API surface which exists in win32 but does not in WRT. Closing those gaps means writing WRT components. This isn't a WRT specific thing either. The same dynamic has existed with Java for 20+ years. The same dynamic exists with Web APIs.

I wish people would stop calling Store apps "modern" as well. If your stuff can go in the store it is often because you are doing something done before (sometimes ad nauseum), not modern. Ditto for the Web. So by analogy say you are Netflix circa 2010, and want to do something "modern", you have to break out of the Web API sandbox. You can't do what you need to do, because the APIs aren't there to do it. Once the Web APIs are there by way of html5, it isn't very modern anymore, is it.

In my use case I don't need admin privileges, but UWP's "Base Privileges" don't work, because surface I need is blocked and/or does not exist. So fine I'll marshal my way out of sandbox jail, if that's what I have to do.

You can say about my use case something along the lines of: "it seems like very little of your scenario is actually intended to be addressed by UWP apps". And you wouldn't be wrong. You can also say, rightfully, that it isn't in cppwinrt's wheelhouse (hey we just project what they give us). Not wrong there either. 

But I think cppwinrt might make writing apps that are actually modern a better experience.

**Comment by nvictor** [comment] 2017-09-01 19:26
voted (https://aka.ms/windowsui/inwin32) to have the UI team deliver if they can.

**Comment by Zingam** [comment] 2017-09-06 16:19
What made Windows and MS big was that it was an Open OS that everybody could write and distribute software for. UWP goes against that very principle what made Windows and MS dominate the PC.
In case of games having to write one version for Steam (Win32) and one for Windows Store/Xbox (WinRT) is a really huge waste of resources.

**Closed** 2017-09-06 16:23 UTC
