### ISSUE TITLE
MDMERGE : error MDM2009: Duplicate type for transitive indirect winmd or project references #318

### ISSUE THREAD

**Issue by mediabuff** [microsoft/cppwinrt#453] opened 2019-12-18 02:29 UTC
Revisiting this after some time. Tried the latest set of tools - same issue.
MDMERGE : error MDM2009: Duplicate type Microsoft.Graphics.Canvas.Effects.IBlendEffect found processing metadata file C:\MyDevProjects\MyProjects\VideoApp\Debug\AudioVisualizer\Win32\Microsoft.Graphics.Canvas.winmd, type already exists in file C:\MyDevProjects\MyProjects\VideoApp\packages\Win2D.uwp.1.24.0\lib\uap10.0\Microsoft.Graphics.Canvas.winmd.

I have a dll and an app referencing the win2d package Microsoft.Graphics.Canvas . Both the dll and the app consume win2d. Additionally, the app consumes the dll as well. Thus the canvas.winmd is getting merged twice at the point of app compilation.

**Comment by kennykerr** [comment] 2019-12-18 02:34
I assume this is an issue with the cppwinrt NuGet package and related msbuild support? We don't have anyone actively working on the build support at the moment. While I'm aware of a few issues, there isn't a whole lot I can do about that at the moment. Feel free to contribute a fix if you find a workaround.

**Comment by kennykerr** [comment] 2019-12-18 02:35
Actually it sounds like a duplicate of https://github.com/microsoft/cppwinrt/issues/452

**Closed** 2019-12-18 02:36 UTC
