### ISSUE TITLE
VS Pro 2022 Preview installation failure

### ISSUE THREAD

**Issue by matthewacme** [microsoft/cppwinrt#995] opened 2021-08-05 18:45 UTC
I realize that 2022 is still in preview but I thought you might like the information.

![image](https://user-images.githubusercontent.com/11168104/128404301-df132046-d642-4d51-899c-39caf936d05f.png)
[dd_VSIXInstaller_20210805144054_0134.log](https://github.com/microsoft/cppwinrt/files/6940998/dd_VSIXInstaller_20210805144054_0134.log)

**Comment by sylveon** [comment] 2021-08-05 19:59
See https://github.com/microsoft/cppwinrt/issues/960#issuecomment-886961817

**Comment by kennykerr** [comment] 2021-08-06 17:27
@DefaultRyan I published a new version with your fixes but it still has the same cycle issue.

**Comment by kennykerr** [comment] 2021-08-13 14:43
Duplicate of #960

**Closed by kennykerr** 2021-08-13 14:43 UTC
Labels: bug
