### ISSUE TITLE
I'm getting errors when I include "<robuffer.h>" in UWP 

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/cppwinrt#117] opened 2017-02-22 18:25 UTC
![image](https://cloud.githubusercontent.com/assets/6119906/23226115/6f720a9e-f902-11e6-802d-29e8a2e45232.png)

**Comment by BrentRe** [comment] 2017-02-22 20:29
This is a duplicate of #116 so closing this one.

**Closed by BrentRe** 2017-02-22 20:29 UTC
