### ISSUE TITLE
A cycle was detected in the dependency graph: Microsoft.VisualStudio.ComponentGroup.UWP.VC when attempting to install the c++ winrt extension.

### ISSUE THREAD

**Issue by TheEndHunter** [microsoft/cppwinrt#1000] opened 2021-08-13 07:28 UTC
when trying to install this Extension from vs2022 preview 3 I get an error -> A cycle was detected in the dependency graph: Microsoft.VisualStudio.ComponentGroup.UWP.VC when attempting to install the c++ winrt extension.

I thought at first that it was a vs2022 issue like with preview 2 so opened [This request](https://developercommunity.visualstudio.com/t/A-cycle-was-detected-in-the-dependency-g/1502078?space=8&scope=follow&sort=newest) but it has been closed and I have been redirected here.

[Collect.exe Logs](https://github.com/microsoft/cppwinrt/files/6980583/vslogs.zip)

[VS Installer Log](https://github.com/microsoft/cppwinrt/files/6980584/dd_VSIXInstaller_20210813081808_23b0.log)

**Comment by sylveon** [comment] 2021-08-13 07:39
See https://github.com/microsoft/cppwinrt/issues/960#issuecomment-886961817

**Comment by kennykerr** [comment] 2021-08-13 14:43
Duplicate of #960

**Closed by kennykerr** 2021-08-13 14:43 UTC
