### ISSUE TITLE
Extra *contract.winmd file dropped in UWP package, leads to "Windows App Certification Kit" failure

### ISSUE THREAD

**Issue by yl-msft** [microsoft/cppwinrt#738] opened 2020-09-05 18:48 UTC
Our team's app were blocked by Store due to "Windows App Certification Kit" failure.  Errors like following
> The types in the Windows.AI.MachineLearning namespace are located in file Windows.AI.MachineLearning.MachineLearningContract.winmd that does not match the namespace.
The types in the Windows.AI.MachineLearning.Preview namespace are located in file Windows.AI.MachineLearning.Preview.MachineLearningPreviewContract.winmd that does not match the namespace.
>...

We found this is due to extra "*Contract.winmd" files dropped in to UWP package root folder.

This regression is introduced between cppwinrt nuget package version 2.0.200609.3 (good) and version 2.0.200615.7 (bad)

This has been reported in stackoverflow independently
https://stackoverflow.com/questions/63025772/uwp-app-failing-windows-app-certification-kit-tests-windows-runtime-metadata-va

We suspect this can repro in any UWP C++ Xaml app using cppwinrt nuget package.  If you need please contact us for repros.

**Comment by DefaultRyan** [comment] 2020-09-05 21:15
Thanks for the detailed version diff. There's not a lot of changes between those versions, and the only likely culprit is
- #612 Set better defaults for references and project references to keep MdMerge happy.

@jlaanstra, could you look into this?

**Comment by brycehutchings** [comment] 2020-09-08 19:27
When I take a C++/WinRT app like the Calendar app (https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/Calendar/cppwinrt/) and build it, none of these extra *Contract.winmd files are included. Then I upgrade the NuGet version of cppwinrt to the latest and repackage the app and now it has all of the extra *Contract.winmd files and fails WACK. We are using the latest version of Visual Studio, and we this this must be related, because version of cppwinrt that worked before no longer work for us. We're still scratching our heads.

**Comment by yl-msft** [comment] 2020-09-08 19:33
We discovered some information that might be useful for debugging this issue.
We found that for the <Reference include="...Contract.winmd"> node in msbuild, the <Private>false</Private> parameter can avoid copying the winmd file to the UWP package root folder.

This is related to this comment in C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets

> The 'Private' attribute on the reference corresponds to the Copy Local flag in IDE.
> The 'Private' flag can have three possible values:
>  - 'True' means the reference should be Copied Local
> - 'False' means the reference should not be Copied Local
> - [Missing] means this task will decide whether to treat this reference as CopyLocal or not.

**Comment by jlaanstra** [comment] 2020-09-15 22:42
I believe this might be fixed by #704

**Comment by brycehutchings** [comment] 2020-09-15 22:52
I guess I'm a bit confused because it seems like it currently isn't possible to build an app that can pass WACK (and thus make it into the Microsoft Store) with C++/WinRT as-is, which I would think would be a big problem. Is that what #704 is fixing? Our best guess is something outside of C++/WinRT (a VS update perhaps?) caused this regression. We can't get the simplest C++/WinRT UWP app to pass WACK anymore.

**Comment by jlaanstra** [comment] 2020-09-16 00:05
@brycehutchings #704 fixes the case where we copy all references to the output folder by default. This was initially done to work around some mdmerge issues. #704 scopes the change down and allows opt out. You should be able to override this in the project file by setting Private to false as you already mentioned until we have a package out with this fix.

**Comment by brycehutchings** [comment] 2020-09-16 01:06
@jlaanstra I don't think we can set Private on the ones from the Windows SDK though. For example, we aren't explicitly using Windows.AI.MachineLearning or referencing it in any way, but we still have a Windows.AI.MachineLearning.MachineLearningContract.winmd in the final appx file that WACK complains about.

**Comment by yl-msft** [comment] 2020-09-16 01:42
@jlaanstra   we can only set <Private> to those we explicitly added reference to.  The Nuget package of cppwinrt added a few dozen new references implicitly, and we have nowhere to add this <Private> parameter.   They all generating WACK errors for our app.

**Comment by kennykerr** [comment] 2020-09-22 21:06
@BenJKuhn do we have anyone knowledgeable about the WACK to look at this?

**Comment by BenJKuhn** [comment] 2020-09-22 22:55
Looking at the cppwinrt build versions / dates, I would suspect this change is the cause of the problem:
https://github.com/microsoft/cppwinrt/pull/679

Windows.* namespaces should be excluded from the package. It's a little unusual that Windows system types are described in metadata shipped in a nuget package. @jonwis, do you want to take a go at this?

**Comment by jlaanstra** [comment] 2020-09-23 05:07
@yl-msft can you try the latest package to see if the issue is resolved?

**Comment by jonwis** [comment] 2020-09-23 17:54
While investigating, I noticed that something in VS2019 or the build chain for "Publish Packages" is modifying package.appxmanifest on disk from:

```xml
<?xml version='1.0' encoding='utf-8'?>
```

To:

```xml
<?xml version='1.0' encoding='utf-8"?>
```

... splatting a \" over the \' in the encoding attribute specification. Super weird.

**Comment by kennykerr** [comment] 2020-10-06 16:27
Feel free to keep the conversation going, or reopen this issue if the latest version didn't resolve the issue as Johan suggested.

**Closed by kennykerr** 2020-10-06 16:27 UTC
Labels: question
